// blocks/applications/image-layouts/svelte/004-featured.svelte
<section class="grid gap-4">
	<!-- Featured -->
	<header>
		<img class="w-full aspect-video bg-surface-500 rounded-container" src="https://picsum.photos/960/512?random=1" alt="Featured" />
	</header>
	<!-- Row -->
	<div class="grid grid-cols-5 gap-4">
		<img class="h-full w-full bg-surface-500 rounded-container" src="https://picsum.photos/200/200?random=2" alt="" />
		<img class="h-full w-full bg-surface-500 rounded-container" src="https://picsum.photos/200/200?random=3" alt="" />
		<img class="h-full w-full bg-surface-500 rounded-container" src="https://picsum.photos/200/200?random=4" alt="" />
		<img class="h-full w-full bg-surface-500 rounded-container" src="https://picsum.photos/200/200?random=5" alt="" />
		<img class="h-full w-full bg-surface-500 rounded-container" src="https://picsum.photos/200/200?random=6" alt="" />
	</div>
</section>

// blocks/applications/image-layouts/react/004-featured.tsx
export default function Featured() {
	return (
		<section className="grid gap-4">
			{/* Featured */}
			<header>
				<img className="w-full aspect-video bg-surface-500 rounded-container" src="https://picsum.photos/960/512?random=1" alt="Featured" />
			</header>
			{/* Row */}
			<div className="grid grid-cols-5 gap-4">
				<img className="h-full w-full bg-surface-500 rounded-container" src="https://picsum.photos/200/200?random=2" alt="" />
				<img className="h-full w-full bg-surface-500 rounded-container" src="https://picsum.photos/200/200?random=3" alt="" />
				<img className="h-full w-full bg-surface-500 rounded-container" src="https://picsum.photos/200/200?random=4" alt="" />
				<img className="h-full w-full bg-surface-500 rounded-container" src="https://picsum.photos/200/200?random=5" alt="" />
				<img className="h-full w-full bg-surface-500 rounded-container" src="https://picsum.photos/200/200?random=6" alt="" />
			</div>
		</section>
	);
}
